name: synapse_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  http: ^1.6.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.2.3
  intl: ^0.19.0
  flutter_launcher_icons: "^0.13.1"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#4DFED1"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/images/mapel/
      - assets/images/pembiasaan/
      - assets/icons/
